[build]
target = "kernel/x86_64-ospab.json"

[target.'cfg(target_os = "none")']
runner = "qemu-system-x86_64"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]